# Gunakan base image bawaan Home Assistant
ARG BUILD_FROM=ghcr.io/home-assistant/aarch64-base:latest
FROM ${BUILD_FROM}

# Tambahkan Python
RUN apk add --no-cache python3 py3-pip

# Folder kerja di dalam container
WORKDIR /app

# Salin semua file ke /app
COPY . /app

# Pastikan file bisa dijalankan
RUN chmod +x /app/run.sh
RUN chmod +x /app/main.py

# Jalankan script utama
CMD ["/app/run.sh"]
