name: "Comfort Entity Cleanup"
version: "1.0.0"
slug: "comfort_entity_cleanup"
description: "Cleanup entitas Comfort tak terpakai"
arch:
  - aarch64
  - amd64
  - armv7
startup: "once"
boot: "manual"
options: {}
schema: {}
