name: "Comfort Entity Cleanup"
version: "1.0.0"
slug: "comfort_entity_cleanup"
description: "Automatically remove unavailable entities caused by deleted YAML"
arch:
  - armv7
startup: services
boot: manual
options: {}
schema: {}
