name: Comfort Entity Cleanup
version: "1.0.0"
slug: comfort_entity_cleanup
description: Automatically removes unavailable entities caused by deleted YAML files.
startup: services
boot: auto
homeassistant_api: true
init: false
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
options: {}
schema: {}
