name: "Comfort Entity Cleanup"
version: "1.0.0"
slug: "comfort_entity_cleanup"
description: "Membersihkan entitas Comfort yang tidak ada di YAML Home Assistant."
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: "services"
boot: "auto"
options:
  HA_URL: "http://supervisor/core"
  HA_TOKEN: ""
schema:
  HA_URL: "str"
  HA_TOKEN: "str"
image: "local/comfort_entity_cleanup"
