ARG BUILD_FROM=ghcr.io/hassio-addons/base:15.0.6
FROM ${BUILD_FROM}

RUN apk add --no-cache python3 py3-pip

WORKDIR /app
COPY . /app

RUN chmod +x /app/run.sh
RUN chmod +x /app/run.py

RUN pip install --no-cache-dir -r requirements.txt || true

CMD [ "/app/run.sh" ]
